snmp:
  community: "public"
  network: "10.80.1.0/24"
  timeout: 3  # 超时时间（秒）
  retries: 1  # 重试次数

db:
  url: sqlite:///data/mactracker.db

schedule:
  interval_minutes: 60
  cleanup_hour: 1
  cleanup_minute: 0
